### ISSUE TITLE
Roll back changes \ Latest development update not working

### ISSUE THREAD

**Issue by Nixellion** [qooob/authentic-theme#895]
Hello,

I just used Force update to development version, and it was a bad idea, because now nothing works. Side-bar appears, but there's no dashboard and buttons only add #other anchors into the url, without any effect.

How do I fix it, or how do I roll back to stable version?

Update:
Log out button worked, and now I can't login, because of the following error:

```
Error - No cookies

Your browser does not support cookies, which are required for this web server to work in session authentication mode
```

**Comment by qooob** [comment]
It's already fixed on my local machine.

To roll back just go to the console, to theme's directory and run update script. You can read more about it on the main page (README.md) file.

**Comment by qooob** [comment]
This bug happens on slow machines.

I'm sorry. To many things to look over.

**Comment by Nixellion** [comment]
Thanks, I'll take a look.

But my machine is not slow. It's a gaming rig repurposed into home-server, it runs on Intel Core i7 2600 with 8 cores and 3.4 GHZ, and I'm accessing web ui from a similar machine.

**Comment by qooob** [comment]
It shouldn't be the cookie issue. What I just fixed was other issue.

Your machine sounds good.

What's your client side OS and the browser?

**Comment by Nixellion** [comment]
Win10, Chrome

I would also appreciate if you could point me in direction of webmin theme directory :)

**Comment by myopenflixr** [comment]
I am experiencing the same thing. I just updated the latest patch and nothing is working. I too have a pretty powerful server.

Here's a screenshot after I log in. Left menu is not responding. I tried this from Firefox and Chrome on client side.
![screenshot](https://user-images.githubusercontent.com/33140130/32921215-bc9565da-cafa-11e7-87a6-da340c77d618.png)

**Comment by Nixellion** [comment]
I was able to sign back in after clearig cookies for the past few days. But it did not fix anything.

Then, if I click the "gears' button on the bottom, the 'settings' one or whatever it is, I get into Webmin Themes and I can move through menus. But buttons don't work there, so i can't use it to update.

**Comment by myopenflixr** [comment]
I was able to get to theme menu via link at bottom of left menu, but I clicking on Force Update to Stable Version is not responding (just like side menu)

**Comment by myopenflixr** [comment]
Ditto Nixellion's comment

**Comment by qooob** [comment]
It depend on the distro.

RHEL is `/usr/libexec/webmin` and Debian like is `/usr/share/webmin`.

FreeBSD - you should know. 😉

**Comment by Nixellion** [comment]
It's debian, ubuntu, thanks. I'm not THAT far into unix systems yet to use FreeBSD :D

**Comment by myopenflixr** [comment]
What would be our solution to manually "install" stable version of Authentic Theme since it cannot be done via Webmin? I'm running Ubuntu Server 16.04.

**Comment by Nixellion** [comment]
I located and ran `theme-update.sh` script at `/usr/share/webmin/authentic-theme` folder, it worked:

```
Would you like to update Authentic Theme for Webmin? [y/N] y
Pulling in latest changes for Authentic Theme (https://github.com/qooob/authentic-theme)...
Updating to Authentic Theme 19.02-git-201711141427, done.
Restarting Webmin..
```

But nothing changed, I suppose it updated to the same version anyway.

**Comment by qooob** [comment]
Guys, it's fairly easy to update it using command line. Other option is to run from browser's console `theme.update(1)`.

**Comment by Nixellion** [comment]
@qooob See above, update did not fix anything, as right now we would probably need to **down**grade.

**Comment by myopenflixr** [comment]
@qooob....what file can we change that holds the setting for "Stable Release" so that when we run theme-update.sh it will downgrade to latest Stable version?

**Comment by qooob** [comment]
Try `theme-update.sh -h`. I think you need to add `-release` switch.

The easiest would be to run console command above.

**Comment by Nixellion** [comment]
Worked, thanks.

```
Would you like to update Authentic Theme for Webmin? [y/N] y
Pulling in latest release of Authentic Theme 19.02 (https://github.com/qooob/authentic-theme)...
Updating to Authentic Theme 19.02-1, done.
Restarting Webmin..

```

**Comment by myopenflixr** [comment]
Worked for me too. But, I'm already missing some of the recent changes you've made in the beta releases
 :(

**Comment by qooob** [comment]
Great.

Tomorrow everything will shine.

Adding new functionality that changing global scope a bit.

This bug affects all that having no Virtualmin and/or no Cloudmin (when Dashboard switch is displayed).

Please keep the issue opened meanwhile. I'll take care of it.

**Comment by myopenflixr** [comment]
Thanks qooob! Your customer service skills are quick and great!

**Comment by qooob** [comment]
Thank you for reporting. ☺️

**Comment by myopenflixr** [comment]
:ok_hand:

**Comment by Nixellion** [comment]
While we're at it, don't want to spam with another issue - how do I switch to the dark version of the theme? Can't find it anywhere

**Comment by qooob** [comment]
Crescent like icon in the row of where logout button is. I remember adding hot key for that. I think `Alt+K`.

**Comment by Nixellion** [comment]
Yeah, thanks, I actually just found it after reading that it's called 'night mode' and saw the 'crescent' button there, made a connection :D Sorry, it's late here, thinking slow.

You're great guys, thanks! 
and great theme :)

**Comment by gnadelwartz** [comment]
seems to be more effort than expected, hope you are not to much stressed

**Comment by qooob** [comment]
The latest git version contains fixed version already. I will close this issue.

Thank you for reporting.
